package model;
// Generated Apr 24, 2014 8:58:04 PM by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Utenti generated by hbm2java
 */
@Entity
@Table(name="utenti"
    ,catalog="ticketweb"
)
public class Utenti  implements java.io.Serializable {


     private String userId;
     private String userPwd;
     private String firstName;
     private String lastName;
     private Date lastUpdate;

    public Utenti() {
        this.userId = "";
    }

    public Utenti(String userId, String userPwd, String firstName, String lastName, Date lastUpdate) {
       this.userId = userId;
       this.userPwd = userPwd;
       this.firstName = firstName;
       this.lastName = lastName;
       this.lastUpdate = lastUpdate;
    }
   
     @Id 

    
    @Column(name="user_id", unique=true, nullable=false, length=20)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="user_pwd", nullable=false, length=20)
    public String getUserPwd() {
        return this.userPwd;
    }
    
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    
    @Column(name="first_name", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }




}


